# Generated by Django 5.0 on 2023-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('experiments', models.ManyToManyField(blank=True, related_name='sample_related', related_query_name='sample', to='scpca_portal.experiment')),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='experiment_related', related_query_name='experiment', to='scpca_portal.sample'),
        ),
    ]
